<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

<ItemGroup>
    <PackageReference Include="Blazored.FluentValidation" Version="2.2.0" />
    <PackageReference Include="BuildBundlerMinifier2022" Version="2.9.11" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.5" />
</ItemGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.0" PrivateAssets="all" />
  </ItemGroup>


  <ItemGroup>
		<Watch Include="**/*.scss" />
		<None Update="**/*.css" Watch="false" />
	</ItemGroup>

   <ItemGroup>
		<ProjectReference Include="..\BlazingTrails.Shared\BlazingTrails.Shared.csproj" />
		<ProjectReference Include="..\BlazingTrails.ComponentLibrary\BlazingTrails.ComponentLibrary.csproj" />
	</ItemGroup>

   <ItemGroup>
     <_ContentIncludedByDefault Remove="Features\Auth\Authentication.razor" />
     <_ContentIncludedByDefault Remove="Features\Auth\LoginStatus.razor" />
   </ItemGroup>


	<Target Name="CheckForNpm" BeforeTargets="RunNpmInstall">
		<Exec Command="npm --version" ContinueOnError="true">
			<Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
		</Exec>
		<Error Condition="'$(ErrorCode)' != '0'" Text="NPM is required to build this project." />
	</Target>

	<Target Name="RunNpmInstall" BeforeTargets="CompileScopedScss" Inputs="package.json" Outputs="$(NpmLastInstall)">
		<Exec Command="npm install" />
		<Touch Files="$(NpmLastInstall)" AlwaysCreate="true" />
	</Target>

	<Target Name="CompileScopedScss" BeforeTargets="Compile">
		<ItemGroup>
			<ScopedScssFiles Include="Features/**/*.razor.scss" />
		</ItemGroup>

		<Exec Command="npm run sass -- %(ScopedScssFiles.Identity) %(relativedir)%(filename).css" />
	</Target>


</Project>
